i1=int(input('Enter the number : '))
i2=int(input('Enter the number : '))
i3=int(input('Enter the number : '))
i4=int(input('Enter the number : '))
i5=int(input('Enter the number : '))
i6=int(input('Enter the number : '))
i7=int(input('Enter the number : '))
i8=int(input('Enter the number : '))
set=set()
set.add(i1)
set.add(i2)
set.add(i3)
set.add(i4)
set.add(i5)
set.add(i6)
set.add(i7)
set.add(i8)
print(set)